# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBooking():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_booking(self):
    self.driver.get("http://localhost:5000/")
    self.driver.set_window_size(1552, 832)
    self.driver.find_element(By.LINK_TEXT, "Buy Tickets").click()
    self.driver.find_element(By.ID, "name").click()
    self.driver.find_element(By.ID, "name").send_keys("kiran kumar")
    self.driver.find_element(By.ID, "contact_number").click()
    self.driver.find_element(By.ID, "contact_number").send_keys("8660220771")
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.ID, "contact_number").click()
    self.driver.find_element(By.CSS_SELECTOR, "html").click()
    self.driver.find_element(By.ID, "no_of_tickets").click()
    self.driver.find_element(By.ID, "no_of_tickets").send_keys("2")
    self.driver.find_element(By.ID, "payment_method").click()
    dropdown = self.driver.find_element(By.ID, "payment_method")
    dropdown.find_element(By.XPATH, "//option[. = 'Debit Card']").click()
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
    self.driver.find_element(By.ID, "cardNumber").click()
    self.driver.find_element(By.ID, "cardNumber").send_keys("123456789")
    self.driver.find_element(By.ID, "cardHolder").click()
    self.driver.find_element(By.ID, "cardHolder").send_keys("kiran")
    self.driver.find_element(By.ID, "expiryDate").click()
    self.driver.find_element(By.ID, "expiryDate").send_keys("12/24")
    self.driver.find_element(By.ID, "cvv").click()
    self.driver.find_element(By.ID, "cvv").send_keys("123")
    self.driver.find_element(By.CSS_SELECTOR, "button").click()
  
